### ISSUE TITLE
Make it work with React.PureComponent

### ISSUE THREAD

**Issue by moimael** [researchgate/babel-plugin-react-class-display-name#4]
Since React 15.3.0, we can now extends from React.PureComponent.

It would be nice to have support for it !

Thanks !

**Comment by aikar** [comment]
walking entire extends tree would be preferred, as I have my own abstract class that provides does some helper stuff for us and provides common util actions. 

then that would handle the PureComponent case too.

**Comment by danez** [comment]
Feel free to implement. We are not using this plugin anymore and could also add maintainers.
